# Generated by Django 6.0.3 on 2026-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_course_user_faculty'),
        ('resources', '0002_remove_module_course_remove_topic_module_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='course',
        ),
        migrations.AddField(
            model_name='user',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='students', to='resources.course'),
        ),
    ]
