# Generated by Django 6.0.3 on 2026-04-05 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='module',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_module__a08798_idx',
        ),
        migrations.RemoveIndex(
            model_name='resource',
            name='resources_module__1c0f44_idx',
        ),
        migrations.AddField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='resources.course'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'cached_score'], name='resources_course__135d84_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['course', 'upload_date'], name='resources_course__0773da_idx'),
        ),
        migrations.RemoveField(
            model_name='resource',
            name='module',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
